spring.application.name=genAi

management.endpoints.web.exposure.include=*
#spring.ai.ollama.chat.model=llama3.2:1b
spring.ai.ollama.chat.options.model=llama3.2:1b
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=all-minilm
